services:

  nats-server:
    build: ./microservice-gateway/nats
    ports:
      - 4222:4222

  microservice-gateway:
    build: 
      context: ./microservice-gateway
      dockerfile: dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000

  beneficiary-microservice:
    build: 
      context: ./beneficiary-microservice
      dockerfile: dockerfile.prod

  general-microservice:
    build: 
      context: ./general-microservice
      dockerfile: dockerfile.prod

  auth-microservice:
    build: 
      context: ./auth-microservice
      dockerfile: dockerfile.prod

  kiosk-microservice:
    build: 
      context: ./kiosk-microservice
      dockerfile: dockerfile.prod